services:
  nginx:
    restart: always
    depends_on:
      - frontend
      - backend
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    ports:
      - "80:8000"

  backend:
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_USER=postgres
      - DB_HOST=db
      - DB_DATABASE=uxsleuth
      - DB_PASSWORD=password
      - DB_PORT=5432
      - NODE_ENV=production
      - PUBLIC_URL=https://uxsleuth.com
  
  job-processor:
    restart: always
    build:
      context: ./job-processor
      dockerfile: Dockerfile.prod
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_USER=postgres
      - DB_HOST=db
      - DB_DATABASE=uxsleuth
      - DB_PASSWORD=password
      - DB_PORT=5432
      - NODE_ENV=production
      - OPENAI_API_KEY=...
      - BROWSERLESS_API_TOKEN=...

  frontend:
    restart: always
    build:
      context: ./client
      dockerfile: Dockerfile.prod
      args:
        - PORT=3000
        - VITE_APP_ENV=production
        - VITE_APP_HOST=https://uxsleuth.com/api

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=uxsleuth
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
