services:
  nginx:
    restart: always
    depends_on:
      - frontend
      - backend
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - "80:8000"

  backend:
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_USER=postgres
      - DB_HOST=db
      - DB_DATABASE=uxsleuth
      - DB_PASSWORD=password
      - DB_PORT=5432
      - NODE_ENV=development
      - PUBLIC_URL=http://localhost
  
  job-processor:
    restart: always
    build:
      context: ./job-processor
      dockerfile: Dockerfile.dev
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_USER=postgres
      - DB_HOST=db
      - DB_DATABASE=uxsleuth
      - DB_PASSWORD=password
      - DB_PORT=5432
      - NODE_ENV=development
      - OPENAI_API_KEY=...
      - BROWSERLESS_API_TOKEN=...

  frontend:
    restart: always
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    environment:
      - VITE_PORT=3000
      - VITE_HMR_SOCKET_PORT=80
      - VITE_APP_ENV=development
      - VITE_APP_DEV_HOST=http://localhost/api
    volumes:
      - /client/node_modules
      - ./client:/client

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=uxsleuth
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
